# Generated by Django 2.2.6 on 2019-11-03 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191103_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 17, 16, 863453, tzinfo=utc)),
        ),
    ]
